version: '3.5'
services:
  db-service:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: questoes-db
    environment:
    - MYSQL_DATABASE=gcquestoes
    - MYSQL_USER=gcquestoes
    - MYSQL_PASSWORD=questoes@123456
    - MYSQL_ROOT_PASSWORD=root
    ports:
    - "3307:3306"
    expose:
    - "3306"
    volumes:
    - ./docker-data/mysql:/var/lib/mysql
    - ./docker-data/migrate:/docker-entrypoint-initdb.d
    networks:
    - gran_network

  web-service:
    # build: ./web
    image: node:latest
    container_name: questoes-web
    working_dir: /home/node/app
    user: "node"
    healthcheck:
      test: ["CMD", "curl", "-sS", "http://localhost:3000"]
      interval: 20s
      timeout: 5s
      retries: 3
    volumes:
    - ./web:/home/node/app
    command:
      sh -c 'cp .env.example .env && npm i && npm run dev'
    ports:
    - "3000:3000"
    environment:
    - NODE_CONFIG_ENV=development
    - NODE_ENV=development
    - BASE_URL=http://localhost:81
    - VUE_WEBAPP_PORT=3000
    links:
    - api-service:questoes-api
    networks:
    - gran_network

  api-service:
    container_name: questoes-api
    build: ./api
    image: clebersantos/php-fpm:1.2.1
    working_dir: /application
    volumes:
    - ./api:/application
    - ./api/docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    environment:
    - UPDATE_COMPOSER_DEPENDENCIES=true
    - USE_PHP_FPM=true
    depends_on:
    - db-service
    links:
    - db-service
    restart: on-failure
    networks:
    - gran_network
  webserver:
    build:
      context: ./api
      dockerfile: WebserverDockerfile
      args:
        EXPOSE_PORT: 80
    image: clebersantos/questoes-webserver-nginx:1.0.0
    container_name: questoes-webserver
    working_dir: /application
    volumes:
    - ./api:/application
    - ./api/docker/webserver/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "81:80"
    depends_on:
    - api-service
    networks:
    - gran_network
networks:
  gran_network:
    name: gran_network
    driver: bridge